/**
 * Writes `dist/sw.js`, with the precache list of the build it is run against.
 *
 *   npm run build && npm run sw
 *
 * ---
 *
 * **Why hand-written and not `vite-plugin-pwa`.** The plugin's two real
 * offerings are manifest generation and precache-manifest generation. This
 * project needs neither badly: the manifest is fourteen static lines that never
 * change, and the precache list is `readdirSync('dist')` — which is what makes
 * the arithmetic lopsided. Priced against the E2 budgets:
 *
 *   this file's output, minified-ish   ~2.2 kB, and none of it in a page chunk
 *   workbox-sw runtime                 ~22 kB, fetched and parsed by the worker
 *   vite-plugin-pwa + workbox-build     ~40 devDependencies
 *
 * Workbox earns those bytes on a site with an API, several origins, expiring
 * caches, background sync and a routing table. This is a single-origin static
 * site with no network calls at all after load — the save is `localStorage` and
 * there is no server — so the whole routing table is two rules, and the twenty
 * kilobytes would be paying for a general answer to a question this app does
 * not ask. The measurement is the argument.
 *
 * What it costs instead is that the two rules below have to be right, which is
 * why they are the only two.
 *
 * **The update path, which matters more than the install.** Stated plainly,
 * because "a service worker that serves a stale shell to a player whose save
 * has moved forward is a corruption path" and this is where that is answered:
 *
 *   - the entry document is **network-first**, with the cache as a fallback and
 *     a short timeout. Online, a load always gets the newest `index.html`,
 *     whose asset URLs are content-hashed and therefore pull that build's own
 *     JavaScript. Offline it gets the shell it has, which is the whole feature;
 *   - everything else is **cache-first**, and that is safe *because* the URLs
 *     are content-hashed: a hashed asset is immutable, so a cache hit cannot be
 *     stale, and a hashed asset the cache has never seen is a new build's and
 *     is fetched;
 *   - the cache is named for the build. A new version's worker fills a new
 *     cache and deletes the old ones only once it activates, so the two builds'
 *     files are never mixed;
 *   - and there is no `skipWaiting`. A tab that is open when a new version
 *     deploys keeps its worker, its cache and its code until it is reloaded
 *     with no other old tab left. Nothing is swapped underneath a running
 *     game, which is what stops an older shell reading a save a newer one has
 *     already migrated. See src/pwa.ts, which argues the same point from the
 *     other end.
 *
 * The residual window is narrow and worth naming rather than hiding: a player
 * whose save has been migrated by a newer build, who then loads again with the
 * network failing, gets the cached older shell. That needs a new deploy, a
 * successful run of it, and a failed network on the very next load — and even
 * then the older code reads the save with its own defaults rather than
 * crashing. Closing it completely would mean refusing to open a save from the
 * future, which is a change to `migrate` and a different prompt.
 */
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const DIST = 'dist';

/** Everything in the build worth holding, bar the sourcemaps. */
function shell(dir = DIST, out = []) {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      shell(path, out);
      continue;
    }
    // Sourcemaps are 4 MB and are fetched only when devtools asks. Precaching
    // them would quadruple what an install costs a player on a phone to buy
    // something no player ever loads.
    if (path.endsWith('.map')) continue;
    // The worker cannot precache itself: it is fetched by the browser's own
    // update check, outside the fetch handler, and a copy in the cache would be
    // a copy that has to be invalidated by something.
    if (entry === 'sw.js') continue;
    out.push(relative(DIST, path).split('\\').join('/'));
  }
  return out;
}

const files = shell().sort();

/**
 * The cache's name, and it has to change whenever any file does.
 *
 * A hash over every precached file's *contents* rather than a version number
 * somebody remembers to bump: the whole point of the cache being named for the
 * build is that two builds can never share one, and a name that depended on a
 * human would eventually not.
 */
const stamp = createHash('sha256');
for (const file of files) {
  stamp.update(file);
  stamp.update(readFileSync(join(DIST, file)));
}
const version = stamp.digest('hex').slice(0, 12);

const worker = `/*
 * District's service worker. Generated by tools/sw.mjs — edit that, not this.
 *
 * Two rules and a cache named for the build. See the header of tools/sw.mjs for
 * why it is hand-written, why the entry document is network-first, and why
 * there is deliberately no skipWaiting.
 */
const CACHE = 'district-${version}';

/**
 * The shell, as URLs relative to this worker's own scope.
 *
 * Relative on purpose: the worker is served beside the page, so its scope is
 * the page's directory — '/' at the dev server and '/idle-city/' on a GitHub
 * project page — and every one of these resolves against it. A leading slash
 * here would be the classic project-page failure, precaching the domain root.
 */
const SHELL = ${JSON.stringify(files, null, 2).replace(/\n/g, '\n')};

/** How long the entry document waits for the network before the cache answers. */
const NETWORK_MS = 2500;

self.addEventListener('install', (event) => {
  // No skipWaiting. A new build waits until no tab is running the old one.
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      // Relative to the worker's scope, and \`reload\` so an install never
      // populates the cache from the browser's own HTTP cache — which could
      // hand this build a previous build's bytes under this build's name.
      cache.addAll(SHELL.map((file) => new Request(new URL(file, self.registration.scope), { cache: 'reload' }))),
    ),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      for (const name of await caches.keys()) {
        if (name !== CACHE && name.startsWith('district-')) await caches.delete(name);
      }
      // Safe without skipWaiting: activation only happens once no client is
      // running the previous build, so there is nothing to swap underneath.
      // What it buys is the very first load, where no worker controlled the
      // page at all and this one can start serving it immediately.
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (!url.pathname.startsWith(new URL(self.registration.scope).pathname)) return;

  // The entry document: network-first, so an online load always gets the
  // newest shell and can never be handed an older build's HTML while the
  // player's save has already moved forward. See tools/sw.mjs.
  if (request.mode === 'navigate') {
    event.respondWith(
      (async () => {
        try {
          const fresh = await Promise.race([
            fetch(request),
            new Promise((_, reject) => setTimeout(() => reject(new Error('slow')), NETWORK_MS)),
          ]);
          const cache = await caches.open(CACHE);
          cache.put(request, fresh.clone());
          return fresh;
        } catch {
          // Offline, or a network slower than the timeout. Either way the
          // player gets their city rather than a browser error page.
          const cached = await caches.match(request, { ignoreSearch: true });
          if (cached) return cached;
          const index = await caches.match(new URL('index.html', self.registration.scope));
          if (index) return index;
          return new Response('Offline, and nothing cached yet.', {
            status: 503,
            headers: { 'content-type': 'text/plain' },
          });
        }
      })(),
    );
    return;
  }

  // Everything else: cache-first, which is correct rather than merely fast
  // because every asset URL is content-hashed. A hit cannot be stale and a miss
  // is a file this build has not seen.
  event.respondWith(
    (async () => {
      const cached = await caches.match(request);
      if (cached) return cached;
      const fresh = await fetch(request);
      if (fresh.ok && fresh.type === 'basic') {
        const cache = await caches.open(CACHE);
        cache.put(request, fresh.clone());
      }
      return fresh;
    })(),
  );
});
`;

writeFileSync(join(DIST, 'sw.js'), worker);

const bytes = (n) => `${n.toLocaleString('en-GB')} B`;
const total = files.reduce((n, file) => n + statSync(join(DIST, file)).size, 0);
console.log('\nService worker\n');
console.log(`  cache            district-${version}`);
console.log(`  precached        ${files.length} files, ${bytes(total)}`);
console.log(`  worker itself    ${bytes(worker.length)}`);
for (const file of files) {
  console.log(`    ${file.padEnd(40)} ${String(statSync(join(DIST, file)).size).padStart(9)} B`);
}
console.log('');
